### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by f1xc0d3** [Boxadactle/coordinates-display#19] opened 2023-05-05 08:34 UTC
https://scans.gradle.com/s/zueyryqkfjk7o

what am I doing wrong?

**Comment by Boxadactle** [comment] 2023-05-21 02:17
Might be caused by modmenu recently moving their maven url, if you were building the fabric version.

**Comment by Boxadactle** [comment] 2023-05-21 02:23
I've configured the dependencies incorrectly, should be fixed in a bit.

**Comment by Boxadactle** [comment] 2023-07-20 06:12
Gradle has been configured completely incorrectly in both Fabric and Forge, finally fixed everything and will be releasing a fixed version soon.

**Closed** 2023-07-25 02:05 UTC
Labels: bug
